name: CI/CD Deployment for Next.js

on:
  push:
    branches:
      - main # Deploy to production
      - uat # Deploy to UAT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the Next.js Application
      - name: Build Next.js App
        run: npm run build

      # Step 5: Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 148.135.136.120
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            if [[ "${{ github.ref_name }}" == "main" ]]; then
              DEPLOY_DIR=/var/www/moneytreerealty
              PM2_APP_NAME="moneytree"
            elif [[ "${{ github.ref_name }}" == "uat" ]]; then
              DEPLOY_DIR=/var/www/uat.moneytreerealty
              PM2_APP_NAME="uat-moneytree"
            fi

            # Navigate to deploy directory
            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR

            # Clean old files
            rm -rf *

            # Transfer new files
            scp -r .next package.json package-lock.json $DEPLOY_DIR/

            # Install dependencies and restart the application
            npm install --production
            pm2 restart $PM2_APP_NAME || pm2 start npm --name $PM2_APP_NAME -- start
